theme = "catppuccin_macchiato"

[editor]
rulers = [80, 120]
mouse = true
line-number = "relative"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
character = "|" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
L = "search"
h = "jump_to_identifier_label"
l = "jump_to_str_label"
"'" = "collapse_selection"
"A-'" = "flip_selections"
C-l = "copy_selection_on_next_line"
A-l = "copy_selection_on_prev_line"

[keys.select]
L = "search"
h = "jump_to_identifier_label"
l = "jump_to_str_label"
"'" = "collapse_selection"
"A-'" = "flip_selections"
C-l = "copy_selection_on_next_line"
A-l = "copy_selection_on_prev_line"
t = "find_till_char"
f = "find_next_char"
T = "till_prev_char"
F = "find_prev_char"
"A-." = "repeat_last_motion"

[keys.normal."#"]
b = ":sh helix-wezterm.sh blame"
c = ":sh helix-wezterm.sh check"
e = ":sh helix-wezterm.sh explorer"
f = ":sh helix-wezterm.sh fzf"
g = ":sh helix-wezterm.sh lazygit"
o = ":sh helix-wezterm.sh open"
r = ":sh helix-wezterm.sh run"
s = ":sh helix-wezterm.sh test_single"
t = ":sh helix-wezterm.sh test_all"
