[[language]]
name = "markdown"
language-servers = ["ltex", "marksman"]
file-types = ["md", "txt"]
scope = "source.markdown"
roots = []

[language-server.ltex]
command = "/home/zelim/opt/lsp/ltex-ls/bin/ltex-ls"
config = { ltex.language = "ru-RU" }

[language-server.marksman]
command= "/home/zelim/opt/lsp/marksman"
